# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-capability-primitives',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-capability-primitives',
                'lib_path': 'cjm_capability_primitives'},
  'syms': {}}
