"""Standardized result DTO for the source-separation (audio-preprocessing) task — the data noun source-separation tool capabilities emit and task adapters / workflow cores consume, wire-registered so results cross the worker boundary typed.

Docs: https://cj-mills.github.io/cjm-capability-primitivessource_separation.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/source_separation.ipynb.

# %% auto #0
__all__ = ['SourceSeparationResult']

# %% ../nbs/source_separation.ipynb #90836580
from dataclasses import dataclass, field
from typing import Any, Dict

from cjm_plugin_system.core.wire import wire_type

# %% ../nbs/source_separation.ipynb #1bf51875
@wire_type("source_separation.result")
@dataclass
class SourceSeparationResult:
    """Standardized output for source-separation (audio-preprocessing) capabilities.

    The payload is an AUDIO ARTIFACT, not inline data: `output_path` is the
    produced isolated-audio file (e.g. the vocals stem) the tool wrote to the
    location the adapter chose. `metadata` carries the stats the fused-era
    return dict held (duration, sample_rate, model, stems_available, and any
    extra-stem paths when the tool was asked to keep them)."""
    output_path: str                                        # Path to the produced isolated-audio artifact (e.g. vocals stem)
    metadata: Dict[str, Any] = field(default_factory=dict)  # Stats (duration, sample_rate, model, stems_available, other_stems, ...)
