"""Standardized result DTO for the voice-activity-detection task — the data noun VAD tool capabilities emit and task adapters / workflow cores consume, wire-registered so results cross the worker boundary typed.

Docs: https://cj-mills.github.io/cjm-capability-primitivesvad.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/vad.ipynb.

# %% auto #0
__all__ = ['TimeRange', 'VADResult']

# %% ../nbs/vad.ipynb #796b41eb
from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional

from cjm_plugin_system.core.wire import wire_type

# %% ../nbs/vad.ipynb #74a8067b
@dataclass
class TimeRange:
    """A temporal segment within an audio source (the VAD speech/silence span)."""
    start: float                                           # Start time in seconds
    end: float                                             # End time in seconds
    label: str = "speech"                                  # Segment type (e.g. 'speech')
    confidence: Optional[float] = None                     # Detection confidence (0.0 to 1.0)
    payload: Dict[str, Any] = field(default_factory=dict)  # Extra data (reserved)

    def to_dict(self) -> Dict[str, Any]:  # Serialized representation
        """Convert to dictionary for JSON serialization."""
        return asdict(self)

# %% ../nbs/vad.ipynb #c454ba1b
@wire_type("vad.result")
@dataclass
class VADResult:
    """Standardized output for voice-activity-detection capabilities."""
    ranges: List[TimeRange]                                 # Detected speech segments, sorted by start
    metadata: Dict[str, Any] = field(default_factory=dict)  # Global VAD stats (duration, sample_rate, total_speech, ...)

    @classmethod
    def from_dict(
        cls,
        d: Dict[str, Any],  # Wire payload (the substrate envelope's "data")
    ) -> "VADResult":  # Reconstructed result with typed ranges
        """Reconstruct from a wire payload, re-typing nested TimeRanges.

        `ranges` holds typed `TimeRange` objects, so the substrate's typed wire
        envelope (stage 2) reconstructs them host-side here rather than leaving
        bare dicts (which would break attribute access like `r.start`).
        """
        return cls(
            ranges=[r if isinstance(r, TimeRange) else TimeRange(**r)
                    for r in (d.get("ranges") or [])],
            metadata=d.get("metadata") or {},
        )
